"""Export GLM-OCR (zai-org/GLM-OCR) to a 4-part ONNX model suite.

## Architecture

GLM-OCR is a vision-language model (VLM) built on Qwen2-VL's architecture.
The HuggingFace model (`AutoModelForImageTextToText`) contains:

    ┌─ model.visual          — ViT vision encoder with M-RoPE (Multi-Resolution
    │                          Rotary Position Embeddings)
    ├─ model.language_model  — Qwen2-based decoder-only LLM (16 layers, GQA)
    │   └─ embed_tokens      — token embedding table (59392 tokens × 1536 dim)
    └─ lm_head               — linear projection → vocab logits

We export this as 4 separate ONNX files:

1. **vision_encoder_mha.onnx** — Exported from native BF16 weights, MHA-optimized.
   MultiHeadAttention fusion for FlashAttention on CUDA.
   Input: pixel_values, pre-computed M-RoPE position IDs, max_grid_size.
   Output: vision hidden states [num_merged_patches, 1536].

2. **embedding.onnx** — Token embedding lookup, split out so the Rust
   runtime can embed tokens without loading the full LLM.
   Input: input_ids [batch, seq_len].
   Output: inputs_embeds [batch, seq_len, 1536].

3. **llm.onnx** — The LLM with dynamic KV cache. Used for the prefill pass
   (single call with full prompt + vision embeddings).
   Input: inputs_embeds, attention_mask, 3D position_ids, past KV cache.
   Output: logits [batch, seq_len, vocab], updated KV cache.

4. **llm_decoder_gqa.onnx** — CUDA-graph-friendly decode-step LLM with
   GroupQueryAttention fusion for FlashAttention V2. Fixed-size KV cache,
   all tensor shapes static for CUDA graph capture/replay.
   Input: input_ids [1,1], step counter, prefill_len, fixed KV cache.
   Output: next_token [1] (ArgMax built in), updated KV cache.

## Precision modes

- **BF16** (default): Native model precision. All models exported directly
  from BF16 weights. Vision encoder Conv/LayerNorm/etc. ops wrapped with FP32
  Cast nodes (ONNX schema rejects BF16 for these). Requires CUDA SM80+.

- **FP16**: Wider ORT compatibility. Lossy conversion from native BF16.

- **FP32**: Debug/validation only. Larger files, slower inference.

## Processor and config files

`export.py` also saves the HuggingFace processor and config to the model
directory via `save_pretrained()`. This produces:

    tokenizer.json, tokenizer_config.json   — BPE tokenizer (59392 vocab)
    config.json                              — model architecture config
    processor_config.json                    — image preprocessor config
    chat_template.jinja                      — chat prompt template

These are needed by both the Python inference scripts (which use
`AutoProcessor.from_pretrained(model_dir)`) and the Rust runtime (which
reads `tokenizer.json` directly via the `tokenizers` crate). They are
auto-generated by this script and gitignored.

Usage:
  python export.py --bf16                # BF16 export (recommended, CUDA SM80+)
  python export.py                       # FP16 export (wider compatibility)
  python export.py --fp32                # FP32 export (debug)
  python export.py --skip-vision         # skip vision encoder
  python export.py --skip-decoder        # skip decoder + GQA optimization
  python export.py --max-seq 256         # decoder max sequence length
"""

import argparse
import sys
import time
import warnings
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import numpy as np
import onnxruntime as ort
import torch
import torch.nn as nn
from transformers import (
    StaticCache,
)
from transformers.cache_utils import StaticLayer

from common.export import (
    MODEL_ID,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_MAX_SEQ,
    NUM_LAYERS,
    NUM_KV_HEADS,
    HEAD_DIM,
    HIDDEN_SIZE,
    VOCAB_SIZE,
    LLMWrapper,
    load_model,
    export_vision_encoder,
    export_embedding,
    export_llm,
    _print_size,
)
from common.onnx_utils import (
    convert_fp32_to_bf16,
    topological_sort,
)


# ── CUDA-specific wrapper modules ────────────────────────────────────────


class WhereStaticLayer(StaticLayer):
    """StaticLayer that uses torch.where instead of index_copy_ for KV updates.

    HuggingFace's default StaticLayer uses `index_copy_()` to write new KV
    entries into the cache buffer at a given position. `index_copy_` exports
    to ONNX as ScatterND, which does indirect addressing (index tensor
    determines write location). Indirect addressing is incompatible with
    CUDA graphs because the index values are read from GPU memory — if the
    buffer address changes between capture and replay, ORT reads garbage
    indices and crashes with ILLEGAL_ADDRESS.

    torch.where exports to ONNX as the Where op, which uses a boolean mask
    computed from a simple comparison (position == cache_position). This is
    fully deterministic and CUDA-graph compatible.
    """

    def update(self, key_states, value_states, cache_kwargs=None):
        if not self.is_initialized:
            self.lazy_initialization(key_states, value_states)

        cache_position = cache_kwargs.get("cache_position") if cache_kwargs is not None else None
        cache_position = (
            cache_position if cache_position is not None else torch.arange(key_states.shape[-2], device=self.device)
        )
        # Build a boolean mask: [1, 1, MAX_SEQ, 1] — True only at cache_position
        positions = torch.arange(self.keys.shape[2], device=self.keys.device)
        mask = (positions == cache_position.squeeze()).view(1, 1, -1, 1)
        # Use Where to do the update: replace at cache_position, keep rest
        self.keys = torch.where(mask, key_states.expand_as(self.keys), self.keys)
        self.values = torch.where(mask, value_states.expand_as(self.values), self.values)
        return self.keys, self.values


class WhereStaticCache(StaticCache):
    """StaticCache using WhereStaticLayer for CUDA-graph-compatible updates."""

    def __init__(self, config, max_cache_len):
        super().__init__(config, max_cache_len=max_cache_len)
        for i, layer in enumerate(self.layers):
            new_layer = WhereStaticLayer(max_cache_len=max_cache_len)
            if layer.is_initialized:
                new_layer.keys = layer.keys
                new_layer.values = layer.values
                new_layer.is_initialized = True
                new_layer.dtype = layer.dtype
                new_layer.device = layer.device
                new_layer.max_batch_size = layer.max_batch_size
                new_layer.num_heads = layer.num_heads
                new_layer.k_head_dim = layer.k_head_dim
                new_layer.v_head_dim = layer.v_head_dim
            self.layers[i] = new_layer


class DecoderStepWrapper(nn.Module):
    """Wraps the GLM-OCR LLM for a single decode step with fixed-size KV cache.

    This is the CUDA-graph-compatible counterpart to LLMWrapper. Key differences:

    | Aspect         | LLMWrapper (prefill)           | DecoderStepWrapper (decode)     |
    |----------------|--------------------------------|---------------------------------|
    | KV cache       | Dynamic (grows each step)      | Fixed MAX_SEQ (write by index)  |
    | Cache type     | DynamicCache (append)          | WhereStaticCache (overwrite)    |
    | Input          | inputs_embeds (pre-embedded)   | input_ids (embeds internally)   |
    | Output         | Full logits [1, seq, 59392]    | next_token [1] (ArgMax built in)|
    | Position IDs   | External (caller computes)     | Internal (derives from step)    |
    | Attention mask | External 2D (caller passes)    | Internal 4D causal mask         |
    | CUDA graph     | Incompatible (dynamic shapes)  | Compatible (all shapes fixed)   |

    The 4D attention mask is computed internally to avoid GatherND. HuggingFace's
    `create_causal_mask()` generates GatherND when building a 4D mask from a 2D
    mask during ONNX tracing. GatherND does indirect addressing which breaks
    CUDA graphs (same reason as ScatterND). By passing a pre-computed 4D mask,
    we bypass create_causal_mask() entirely (it has an early-exit for 4D input
    at masking_utils.py:788).

    Inputs:
        input_ids:      [1, 1] int64 — single token to decode
        step:           [1] int64 — decode step (0 = first generated token)
        prefill_len:    [1] int64 — length of the prefill KV cache
        past_key_{i}:   [1, 8, MAX_SEQ, 128] × 16 layers
        past_value_{i}: [1, 8, MAX_SEQ, 128] × 16 layers

    Outputs:
        next_token:       [1] int64 — argmax of logits (stays on GPU)
        present_key_{i}:  [1, 8, MAX_SEQ, 128] × 16 layers
        present_value_{i}:[1, 8, MAX_SEQ, 128] × 16 layers
    """

    def __init__(self, model, max_seq: int):
        super().__init__()
        self.embed_tokens = model.model.language_model.embed_tokens
        self.language_model = model.model.language_model
        self.lm_head = model.lm_head
        self.max_seq = max_seq
        self.config = model.config.text_config

    def forward(self, input_ids, step, prefill_len,
                past_key_0, past_value_0, past_key_1, past_value_1,
                past_key_2, past_value_2, past_key_3, past_value_3,
                past_key_4, past_value_4, past_key_5, past_value_5,
                past_key_6, past_value_6, past_key_7, past_value_7,
                past_key_8, past_value_8, past_key_9, past_value_9,
                past_key_10, past_value_10, past_key_11, past_value_11,
                past_key_12, past_value_12, past_key_13, past_value_13,
                past_key_14, past_value_14, past_key_15, past_value_15):

        past_keys = [past_key_0, past_key_1, past_key_2, past_key_3,
                     past_key_4, past_key_5, past_key_6, past_key_7,
                     past_key_8, past_key_9, past_key_10, past_key_11,
                     past_key_12, past_key_13, past_key_14, past_key_15]
        past_values = [past_value_0, past_value_1, past_value_2, past_value_3,
                       past_value_4, past_value_5, past_value_6, past_value_7,
                       past_value_8, past_value_9, past_value_10, past_value_11,
                       past_value_12, past_value_13, past_value_14, past_value_15]

        # Embed the single input token (baked into graph, no separate session call)
        inputs_embeds = self.embed_tokens(input_ids)  # [1, 1, HIDDEN_SIZE]

        # Compute write position in the KV cache
        cache_pos = prefill_len + step  # [1] — where to write new KV entry

        # Build 4D causal attention mask directly, bypassing create_causal_mask()
        # which generates a GatherND op that breaks CUDA graph capture.
        # Shape: [1, 1, 1, MAX_SEQ] — 0.0 for attended, min_dtype for masked
        min_dtype = torch.finfo(inputs_embeds.dtype).min
        positions = torch.arange(self.max_seq, device=input_ids.device)
        attend = positions < (cache_pos + 1)  # [MAX_SEQ] bool
        attention_mask = torch.where(
            attend.view(1, 1, 1, -1),
            torch.tensor(0.0, dtype=inputs_embeds.dtype, device=input_ids.device),
            torch.tensor(min_dtype, dtype=inputs_embeds.dtype, device=input_ids.device),
        )

        # Build 3D M-RoPE position IDs for decode step.
        # During decode, all 3 dims (temporal, height, width) get the same value
        # because we're generating text tokens (not vision tokens).
        position_ids = cache_pos.view(1, 1, 1).expand(3, 1, 1).contiguous()

        # Build WhereStaticCache (uses Where op instead of ScatterND)
        past_key_values = WhereStaticCache(
            config=self.config,
            max_cache_len=self.max_seq,
        )

        # Inject the input KV buffers into the cache layers
        for layer_idx in range(NUM_LAYERS):
            layer = past_key_values.layers[layer_idx]
            layer.keys = past_keys[layer_idx]
            layer.values = past_values[layer_idx]
            layer.is_initialized = True
            layer.dtype = past_keys[layer_idx].dtype
            layer.device = past_keys[layer_idx].device
            layer.max_batch_size = 1
            layer.num_heads = NUM_KV_HEADS
            layer.k_head_dim = HEAD_DIM
            layer.v_head_dim = HEAD_DIM

        # Run the language model with WhereStaticCache + cache_position
        outputs = self.language_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=True,
            cache_position=cache_pos,
        )

        logits = self.lm_head(outputs.last_hidden_state)  # [1, 1, VOCAB_SIZE]

        # Cast to f32 for argmax + log-prob (CUDA EP has no BF16 ArgMax kernel)
        logits_f32 = logits[:, -1, :].float()  # [1, V]

        # Log-softmax → max log-prob (confidence for this token)
        log_probs = torch.nn.functional.log_softmax(logits_f32, dim=-1)  # [1, V]
        token_log_prob = log_probs.max(dim=-1)[0]  # [1]

        # ArgMax for next token — stays on GPU, only 8 bytes to copy per step
        next_token = logits_f32.argmax(dim=-1)  # [1]

        # Extract updated KV cache
        updated_cache = outputs.past_key_values
        result = [next_token, token_log_prob]
        for layer_idx in range(NUM_LAYERS):
            result.append(updated_cache.layers[layer_idx].keys)
            result.append(updated_cache.layers[layer_idx].values)

        return tuple(result)


# ── CUDA-specific export functions ────────────────────────────────────────


def export_decoder(model, output_dir: Path, max_seq: int, export_dtype=torch.bfloat16):
    """Export the CUDA-graph-friendly decode-step LLM.

    Produces llm_decoder.onnx with all-static shapes:
      - KV cache: [1, 8, MAX_SEQ, 128] (fixed, not growing)
      - Input: input_ids [1, 1] + step [1] + prefill_len [1]
      - Output: next_token [1] (ArgMax built into graph)

    No dynamic_axes — every tensor shape is fixed at export time. This is
    required for CUDA graph capture, which records a sequence of GPU kernel
    launches and replays them. Any shape change would invalidate the capture.

    The model weights use export_dtype (BF16 by default), so no post-export
    conversion is needed.
    """
    print(f"\nExporting llm_decoder.onnx (MAX_SEQ={max_seq}, dtype={export_dtype}) ...")

    wrapper = DecoderStepWrapper(model, max_seq).eval().to(export_dtype)

    batch = 1
    seq = 1

    input_ids = torch.randint(0, VOCAB_SIZE, (batch, seq), dtype=torch.long)
    step = torch.tensor([0], dtype=torch.long)
    prefill_len = torch.tensor([10], dtype=torch.long)

    past_kv = []
    for _ in range(NUM_LAYERS):
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, max_seq, HEAD_DIM, dtype=export_dtype))
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, max_seq, HEAD_DIM, dtype=export_dtype))

    input_names = ["input_ids", "step", "prefill_len"]
    output_names = ["next_token", "token_log_prob"]

    for i in range(NUM_LAYERS):
        input_names.extend([f"past_key_{i}", f"past_value_{i}"])
        output_names.extend([f"present_key_{i}", f"present_value_{i}"])

    output_path = output_dir / "llm_decoder.onnx"
    all_inputs = (input_ids, step, prefill_len) + tuple(past_kv)

    torch.onnx.export(
        wrapper,
        all_inputs,
        str(output_path),
        input_names=input_names,
        output_names=output_names,
        opset_version=17,
        do_constant_folding=True,
    )

    _print_size(output_path)
    return output_path


def validate_decoder(output_dir: Path, max_seq: int):
    """Validate the exported decoder ONNX loads and produces correct shapes."""
    print("\nValidating llm_decoder.onnx ...")
    decoder_path = output_dir / "llm_decoder.onnx"

    opts = ort.SessionOptions()
    opts.log_severity_level = 3
    session = ort.InferenceSession(str(decoder_path), opts, providers=["CPUExecutionProvider"])

    print("  Session inputs:")
    for inp in session.get_inputs():
        print(f"    {inp.name}: {inp.type} {inp.shape}")
    print("  Session outputs:")
    for out in session.get_outputs():
        print(f"    {out.name}: {out.type} {out.shape}")

    # Test inference
    feed = {
        "input_ids": np.array([[100]], dtype=np.int64),
        "step": np.array([0], dtype=np.int64),
        "prefill_len": np.array([10], dtype=np.int64),
    }
    # Determine KV cache dtype from the model's first KV input
    kv_dtype_str = session.get_inputs()[3].type  # past_key_0
    if "bfloat16" in kv_dtype_str:
        from ml_dtypes import bfloat16 as ml_bf16
        kv_np_dtype = ml_bf16
    else:
        kv_np_dtype = np.float16
    for i in range(NUM_LAYERS):
        feed[f"past_key_{i}"] = np.zeros(
            (1, NUM_KV_HEADS, max_seq, HEAD_DIM), dtype=kv_np_dtype
        )
        feed[f"past_value_{i}"] = np.zeros(
            (1, NUM_KV_HEADS, max_seq, HEAD_DIM), dtype=kv_np_dtype
        )

    outputs = session.run(None, feed)
    next_token = outputs[0]
    token_log_prob = outputs[1]
    print(f"  next_token: {next_token} (shape={next_token.shape}, dtype={next_token.dtype})")
    print(f"  token_log_prob: {token_log_prob} (shape={token_log_prob.shape}, dtype={token_log_prob.dtype})")

    for i in range(NUM_LAYERS):
        k = outputs[2 + i * 2]
        v = outputs[3 + i * 2]
        assert k.shape == (1, NUM_KV_HEADS, max_seq, HEAD_DIM), \
            f"present_key_{i} shape mismatch: {k.shape}"
        assert v.shape == (1, NUM_KV_HEADS, max_seq, HEAD_DIM), \
            f"present_value_{i} shape mismatch: {v.shape}"

    print("  PASS: all shapes correct")


def validate_llm(wrapper, output_dir: Path, dtype):
    """Validate LLM ONNX output matches PyTorch within precision tolerance."""
    print("\nValidating LLM ...")
    output_path = output_dir / "llm.onnx"
    opts = ort.SessionOptions()
    opts.log_severity_level = 3
    session = ort.InferenceSession(str(output_path), opts, providers=["CPUExecutionProvider"])

    print(f"  Prefill test (dtype={dtype}) ...", flush=True)
    embeds = torch.randn(1, 16, HIDDEN_SIZE, dtype=dtype)
    mask = torch.ones(1, 16, dtype=torch.long)
    pos = torch.arange(16).view(1, 1, -1).expand(3, 1, -1).contiguous().long()
    empty_kv = [torch.zeros(1, NUM_KV_HEADS, 0, HEAD_DIM, dtype=dtype)
                for _ in range(NUM_LAYERS * 2)]

    wrapper = wrapper.to(dtype)
    with torch.no_grad():
        pt_out = wrapper(embeds, mask, pos, *empty_kv)

    onnx_feed = {
        "inputs_embeds": embeds.numpy(),
        "attention_mask": mask.numpy(),
        "position_ids": pos.numpy(),
    }
    for i in range(NUM_LAYERS):
        onnx_feed[f"past_key_{i}"] = empty_kv[i * 2].numpy()
        onnx_feed[f"past_value_{i}"] = empty_kv[i * 2 + 1].numpy()

    onnx_out = session.run(None, onnx_feed)
    diff = np.abs(pt_out[0].float().numpy() - onnx_out[0].astype(np.float32)).max()
    threshold = 1.0 if dtype == torch.float16 else 0.01
    print(f"    logits max diff: {diff:.2e} {'PASS' if diff < threshold else 'FAIL'}")


# ── Main ──────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Export GLM-OCR to ONNX")
    parser.add_argument("--output-dir", type=str, default=DEFAULT_OUTPUT_DIR)
    dtype_group = parser.add_mutually_exclusive_group()
    dtype_group.add_argument("--fp32", action="store_true",
                             help="Export in FP32 (debug)")
    dtype_group.add_argument("--bf16", action="store_true",
                             help="Export all models in BF16 (requires CUDA)")
    parser.add_argument("--skip-vision", action="store_true",
                        help="Skip vision encoder export (use existing file)")
    parser.add_argument("--skip-decoder", action="store_true",
                        help="Skip CUDA-graph decoder export")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine export dtype for embedding + LLM
    if args.fp32:
        export_dtype = torch.float32
    elif args.bf16:
        export_dtype = torch.bfloat16
    else:
        export_dtype = torch.float16

    print(f"Export dtype: {export_dtype}")
    model, processor, config = load_model(export_dtype, output_dir)

    with torch.no_grad():
        # ── Shared models (used by both prefill and non-CUDA-graph decode) ──
        export_embedding(model, output_dir)

        # ── Prefill LLM (dynamic KV cache, runs once per image) ──
        export_llm(model, output_dir, export_dtype)

        # ── Vision encoder (native BF16 → FP32 trace → MHA optimize → FP32→BF16) ──
        if args.skip_vision:
            print("Skipping vision encoder (--skip-vision)")
        else:
            export_vision_encoder(model, output_dir, export_dtype, apply_mha=True)

        # ── Decode-step LLM (fixed KV cache, CUDA graph compatible) ──
        if args.skip_decoder:
            print("\nSkipping decoder (--skip-decoder)")
        else:
            export_decoder(model, output_dir, DEFAULT_MAX_SEQ, export_dtype)
            # GQA attention fusion on the exported decoder
            from optimize_gqa import apply_gqa_surgery
            decoder_path = output_dir / "llm_decoder.onnx"
            gqa_path = output_dir / "llm_decoder_gqa.onnx"
            apply_gqa_surgery(decoder_path, gqa_path, DEFAULT_MAX_SEQ)

    # ── Validation ──
    if args.bf16:
        print("\nSkipping validation (BF16 requires CUDA)")
    else:
        llm_wrapper = LLMWrapper(model).eval()
        validate_llm(llm_wrapper, output_dir, export_dtype)
        if not args.skip_decoder:
            validate_decoder(output_dir, DEFAULT_MAX_SEQ)

    # ── Summary ──
    print(f"\n{'='*50}")
    print("Export complete. Files:")
    total = 0
    for f in sorted(output_dir.glob("*.onnx*")):
        if f.suffix in ('.onnx', '.data'):
            sz = f.stat().st_size / 1024 / 1024
            total += sz
            print(f"  {f.name:40s} {sz:>8.1f} MB")
    print(f"  {'TOTAL':40s} {total:>8.1f} MB")
    if args.bf16:
        print("\nNote: BF16 models require CUDA. Non-BF16 ops (Conv, LayerNorm, Range) use FP32 fallback.")


if __name__ == "__main__":
    main()
