"""Export GLM-OCR (zai-org/GLM-OCR) to a 4-part ONNX model suite.

## Architecture

GLM-OCR is a vision-language model (VLM) built on Qwen2-VL's architecture.
The HuggingFace model (`AutoModelForImageTextToText`) contains:

    ┌─ model.visual          — ViT vision encoder with M-RoPE (Multi-Resolution
    │                          Rotary Position Embeddings)
    ├─ model.language_model  — Qwen2-based decoder-only LLM (16 layers, GQA)
    │   └─ embed_tokens      — token embedding table (59392 tokens × 1536 dim)
    └─ lm_head               — linear projection → vocab logits

We export this as 4 separate ONNX files:

1. **vision_encoder_mha.onnx** — Exported from native BF16 weights, MHA-optimized.
   MultiHeadAttention fusion for FlashAttention on CUDA.
   Input: pixel_values, pre-computed M-RoPE position IDs, max_grid_size.
   Output: vision hidden states [num_merged_patches, 1536].

2. **embedding.onnx** — Token embedding lookup, split out so the Rust
   runtime can embed tokens without loading the full LLM.
   Input: input_ids [batch, seq_len].
   Output: inputs_embeds [batch, seq_len, 1536].

3. **llm.onnx** — The LLM with dynamic KV cache. Used for the prefill pass
   (single call with full prompt + vision embeddings).
   Input: inputs_embeds, attention_mask, 3D position_ids, past KV cache.
   Output: logits [batch, seq_len, vocab], updated KV cache.

4. **llm_decoder_gqa.onnx** — CUDA-graph-friendly decode-step LLM with
   GroupQueryAttention fusion for FlashAttention V2. Fixed-size KV cache,
   all tensor shapes static for CUDA graph capture/replay.
   Input: input_ids [1,1], step counter, prefill_len, fixed KV cache.
   Output: next_token [1] (ArgMax built in), updated KV cache.

## Inference flow (Rust runtime)

    Image → HF Processor → pixel_values, input_ids
    pixel_values → vision_encoder.onnx → vision_embeds
    input_ids → embedding.onnx → token_embeds
    Merge vision_embeds into token_embeds at <image> positions
    merged_embeds → llm.onnx (prefill, 1 call) → first logits + KV cache
    token → llm_decoder.onnx (decode loop, CUDA graph) → next tokens

## Vision encoder export strategy

The vision encoder's rot_pos_emb() uses Python loops with data-dependent
shapes (for t, h, w in grid_thw) that torch.onnx.export can't trace. We
work around this by pre-computing position IDs outside the ONNX model:
the wrapper takes pos_ids [N, 2] and max_grid_size as inputs (computed in
the Rust runtime). Attention is also inlined as standard matmul attention
to avoid the untraceable cu_seqlens splitting path.

## Precision modes

- **BF16** (default): Native model precision. All models exported directly
  from BF16 weights. Vision encoder Conv/LayerNorm/etc. ops wrapped with FP32
  Cast nodes (ONNX schema rejects BF16 for these). Requires CUDA SM80+.

- **FP16**: Wider ORT compatibility. Lossy conversion from native BF16.

- **FP32**: Debug/validation only. Larger files, slower inference.

## Processor and config files

`export.py` also saves the HuggingFace processor and config to the model
directory via `save_pretrained()`. This produces:

    tokenizer.json, tokenizer_config.json   — BPE tokenizer (59392 vocab)
    config.json                              — model architecture config
    processor_config.json                    — image preprocessor config
    chat_template.jinja                      — chat prompt template

These are needed by both the Python inference scripts (which use
`AutoProcessor.from_pretrained(model_dir)`) and the Rust runtime (which
reads `tokenizer.json` directly via the `tokenizers` crate). They are
auto-generated by this script and gitignored.

Usage:
  python export.py --bf16                # BF16 export (recommended, CUDA SM80+)
  python export.py                       # FP16 export (wider compatibility)
  python export.py --fp32                # FP32 export (debug)
  python export.py --skip-vision         # skip vision encoder
  python export.py --skip-decoder        # skip decoder + GQA optimization
  python export.py --max-seq 256         # decoder max sequence length
"""

import argparse
import sys
import time
import warnings
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ── Transformers 5.2.0 monkey-patch ──────────────────────────────────────
#
# transformers 5.2.0 introduced a `video_processing_auto` module with a
# broken `video_processor_class_from_name()` function. It crashes during
# `AutoProcessor.from_pretrained()` when iterating VIDEO_PROCESSOR_MAPPING_NAMES,
# because it doesn't handle None entries or missing attributes.
#
# This patch provides a safe implementation that gracefully handles missing
# modules and None entries. Remove once transformers fixes the bug upstream.

import importlib
import transformers.models.auto.video_processing_auto as _vpa

def _patched_video_processor_class_from_name(class_name):
    for module_name, extractors in _vpa.VIDEO_PROCESSOR_MAPPING_NAMES.items():
        if extractors is None:
            continue
        if class_name in extractors:
            mn = _vpa.model_type_to_module_name(module_name)
            module = importlib.import_module(f".{mn}", "transformers.models")
            try:
                return getattr(module, class_name)
            except AttributeError:
                continue
    for extractor in _vpa.VIDEO_PROCESSOR_MAPPING._extra_content.values():
        if getattr(extractor, "__name__", None) == class_name:
            return extractor
    main_module = importlib.import_module("transformers")
    if hasattr(main_module, class_name):
        return getattr(main_module, class_name)
    return None

_vpa.video_processor_class_from_name = _patched_video_processor_class_from_name

import numpy as np
import onnx
import onnxruntime as ort
import torch
import torch.nn as nn
from transformers import (
    AutoConfig,
    AutoModelForImageTextToText,
    AutoProcessor,
    DynamicCache,
    StaticCache,
)
from transformers.cache_utils import StaticLayer

MODEL_ID = "zai-org/GLM-OCR"
DEFAULT_OUTPUT_DIR = "../model"
DEFAULT_MAX_SEQ = 512

# Model architecture constants (from config.json → text_config).
# GLM-OCR uses Qwen2-based LLM with Grouped Query Attention (GQA):
#   - 16 decoder layers
#   - 12 attention heads, 8 KV heads (GQA ratio 3:2)
#   - head_dim = hidden_size / num_heads = 1536 / 12 = 128
#   - vocab_size = 59392 (including special tokens)
NUM_LAYERS = 16
NUM_KV_HEADS = 8
HEAD_DIM = 128
HIDDEN_SIZE = 1536
VOCAB_SIZE = 59392


# ── Wrapper modules ──────────────────────────────────────────────────────
#
# torch.onnx.export works by TRACING: it runs a PyTorch nn.Module's forward()
# with example inputs, records every tensor operation, and writes those ops
# as ONNX nodes. The resulting ONNX graph is a flattened fusion of ALL code
# that executes during the trace — including HuggingFace library internals,
# our wrapper logic, and the model weights.
#
# The problem: HuggingFace's API uses Python objects (DynamicCache, StaticCache),
# keyword arguments, and optional returns. ONNX only supports flat tensor
# inputs and outputs. These wrappers bridge that gap:
#
#   ONNX flat tensors → wrapper.forward() → HuggingFace Python API → wrapper → ONNX flat tensors
#
# Each wrapper reconstructs the Python objects HuggingFace expects, calls the
# model, then flattens the results back to tensors. The trace captures
# everything that happens inside forward(), including the HuggingFace code.


class EmbedTokensWrapper(nn.Module):
    """Wraps the text embedding layer for standalone ONNX export.

    Extracting embedding as a separate ONNX model lets the Rust runtime
    do token→embedding lookup independently from the LLM forward pass.
    This is used during prefill (embed all prompt tokens at once) and
    also by the non-CUDA-graph decode path (embed one token per step).

    The CUDA-graph decoder (llm_decoder.onnx, see DecoderStepWrapper)
    has the embedding table baked in, so it doesn't need this.
    """

    def __init__(self, model):
        super().__init__()
        self.embed_tokens = model.model.language_model.embed_tokens

    def forward(self, input_ids):
        return self.embed_tokens(input_ids)


class LLMWrapper(nn.Module):
    """Wraps the LLM decoder with explicit flattened KV cache I/O.

    HuggingFace's LLM expects a `DynamicCache` object for KV cache, but
    ONNX only supports flat tensor inputs/outputs. This wrapper:

    1. Takes 32 individual past_key/past_value tensors (16 layers × 2)
       as explicit named parameters
    2. Reconstructs a DynamicCache from them
    3. Calls the HuggingFace LLM
    4. Returns logits + 32 updated KV tensors as a flat tuple

    Why explicit named parameters instead of *args:
    torch.onnx.export in torch 2.10+ has issues mapping dynamic_axes to
    positional *args parameters. Using explicit named parameters
    (past_key_0, past_value_0, ...) ensures dynamic_axes dict keys
    match the actual parameter names reliably.

    The dynamic KV cache means past_seq_len grows by 1 each decode step.
    This is fine for the prefill pass (run once) but incompatible with
    CUDA graphs (which need fixed shapes). See DecoderStepWrapper for the
    fixed-shape alternative used in the decode loop.
    """

    def __init__(self, model):
        super().__init__()
        self.language_model = model.model.language_model
        self.lm_head = model.lm_head

    def forward(self, inputs_embeds, attention_mask, position_ids,
                past_key_0, past_value_0, past_key_1, past_value_1,
                past_key_2, past_value_2, past_key_3, past_value_3,
                past_key_4, past_value_4, past_key_5, past_value_5,
                past_key_6, past_value_6, past_key_7, past_value_7,
                past_key_8, past_value_8, past_key_9, past_value_9,
                past_key_10, past_value_10, past_key_11, past_value_11,
                past_key_12, past_value_12, past_key_13, past_value_13,
                past_key_14, past_value_14, past_key_15, past_value_15):
        past_keys = [past_key_0, past_key_1, past_key_2, past_key_3,
                     past_key_4, past_key_5, past_key_6, past_key_7,
                     past_key_8, past_key_9, past_key_10, past_key_11,
                     past_key_12, past_key_13, past_key_14, past_key_15]
        past_values = [past_value_0, past_value_1, past_value_2, past_value_3,
                       past_value_4, past_value_5, past_value_6, past_value_7,
                       past_value_8, past_value_9, past_value_10, past_value_11,
                       past_value_12, past_value_13, past_value_14, past_value_15]

        # Reconstruct HuggingFace's DynamicCache from flat tensors.
        # DynamicCache stores a list of (key, value) per layer and handles
        # concatenation of new KV pairs during generation.
        past_key_values = DynamicCache()
        for layer in range(NUM_LAYERS):
            past_key_values.update(past_keys[layer], past_values[layer], layer)

        outputs = self.language_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=True,
        )

        logits = self.lm_head(outputs.last_hidden_state)
        new_past = outputs.past_key_values

        # Flatten updated KV cache back to individual tensors for ONNX output.
        # Order: logits, key_0, value_0, key_1, value_1, ...
        result = [logits]
        for layer in range(NUM_LAYERS):
            result.append(new_past.layers[layer].keys)
            result.append(new_past.layers[layer].values)
        return tuple(result)


class WhereStaticLayer(StaticLayer):
    """StaticLayer that uses torch.where instead of index_copy_ for KV updates.

    HuggingFace's default StaticLayer uses `index_copy_()` to write new KV
    entries into the cache buffer at a given position. `index_copy_` exports
    to ONNX as ScatterND, which does indirect addressing (index tensor
    determines write location). Indirect addressing is incompatible with
    CUDA graphs because the index values are read from GPU memory — if the
    buffer address changes between capture and replay, ORT reads garbage
    indices and crashes with ILLEGAL_ADDRESS.

    torch.where exports to ONNX as the Where op, which uses a boolean mask
    computed from a simple comparison (position == cache_position). This is
    fully deterministic and CUDA-graph compatible.
    """

    def update(self, key_states, value_states, cache_kwargs=None):
        if not self.is_initialized:
            self.lazy_initialization(key_states, value_states)

        cache_position = cache_kwargs.get("cache_position") if cache_kwargs is not None else None
        cache_position = (
            cache_position if cache_position is not None else torch.arange(key_states.shape[-2], device=self.device)
        )
        # Build a boolean mask: [1, 1, MAX_SEQ, 1] — True only at cache_position
        positions = torch.arange(self.keys.shape[2], device=self.keys.device)
        mask = (positions == cache_position.squeeze()).view(1, 1, -1, 1)
        # Use Where to do the update: replace at cache_position, keep rest
        self.keys = torch.where(mask, key_states.expand_as(self.keys), self.keys)
        self.values = torch.where(mask, value_states.expand_as(self.values), self.values)
        return self.keys, self.values


class WhereStaticCache(StaticCache):
    """StaticCache using WhereStaticLayer for CUDA-graph-compatible updates."""

    def __init__(self, config, max_cache_len):
        super().__init__(config, max_cache_len=max_cache_len)
        for i, layer in enumerate(self.layers):
            new_layer = WhereStaticLayer(max_cache_len=max_cache_len)
            if layer.is_initialized:
                new_layer.keys = layer.keys
                new_layer.values = layer.values
                new_layer.is_initialized = True
                new_layer.dtype = layer.dtype
                new_layer.device = layer.device
                new_layer.max_batch_size = layer.max_batch_size
                new_layer.num_heads = layer.num_heads
                new_layer.k_head_dim = layer.k_head_dim
                new_layer.v_head_dim = layer.v_head_dim
            self.layers[i] = new_layer


class DecoderStepWrapper(nn.Module):
    """Wraps the GLM-OCR LLM for a single decode step with fixed-size KV cache.

    This is the CUDA-graph-compatible counterpart to LLMWrapper. Key differences:

    | Aspect         | LLMWrapper (prefill)           | DecoderStepWrapper (decode)     |
    |----------------|--------------------------------|---------------------------------|
    | KV cache       | Dynamic (grows each step)      | Fixed MAX_SEQ (write by index)  |
    | Cache type     | DynamicCache (append)          | WhereStaticCache (overwrite)    |
    | Input          | inputs_embeds (pre-embedded)   | input_ids (embeds internally)   |
    | Output         | Full logits [1, seq, 59392]    | next_token [1] (ArgMax built in)|
    | Position IDs   | External (caller computes)     | Internal (derives from step)    |
    | Attention mask | External 2D (caller passes)    | Internal 4D causal mask         |
    | CUDA graph     | Incompatible (dynamic shapes)  | Compatible (all shapes fixed)   |

    The 4D attention mask is computed internally to avoid GatherND. HuggingFace's
    `create_causal_mask()` generates GatherND when building a 4D mask from a 2D
    mask during ONNX tracing. GatherND does indirect addressing which breaks
    CUDA graphs (same reason as ScatterND). By passing a pre-computed 4D mask,
    we bypass create_causal_mask() entirely (it has an early-exit for 4D input
    at masking_utils.py:788).

    Inputs:
        input_ids:      [1, 1] int64 — single token to decode
        step:           [1] int64 — decode step (0 = first generated token)
        prefill_len:    [1] int64 — length of the prefill KV cache
        past_key_{i}:   [1, 8, MAX_SEQ, 128] × 16 layers
        past_value_{i}: [1, 8, MAX_SEQ, 128] × 16 layers

    Outputs:
        next_token:       [1] int64 — argmax of logits (stays on GPU)
        present_key_{i}:  [1, 8, MAX_SEQ, 128] × 16 layers
        present_value_{i}:[1, 8, MAX_SEQ, 128] × 16 layers
    """

    def __init__(self, model, max_seq: int):
        super().__init__()
        self.embed_tokens = model.model.language_model.embed_tokens
        self.language_model = model.model.language_model
        self.lm_head = model.lm_head
        self.max_seq = max_seq
        self.config = model.config.text_config

    def forward(self, input_ids, step, prefill_len,
                past_key_0, past_value_0, past_key_1, past_value_1,
                past_key_2, past_value_2, past_key_3, past_value_3,
                past_key_4, past_value_4, past_key_5, past_value_5,
                past_key_6, past_value_6, past_key_7, past_value_7,
                past_key_8, past_value_8, past_key_9, past_value_9,
                past_key_10, past_value_10, past_key_11, past_value_11,
                past_key_12, past_value_12, past_key_13, past_value_13,
                past_key_14, past_value_14, past_key_15, past_value_15):

        past_keys = [past_key_0, past_key_1, past_key_2, past_key_3,
                     past_key_4, past_key_5, past_key_6, past_key_7,
                     past_key_8, past_key_9, past_key_10, past_key_11,
                     past_key_12, past_key_13, past_key_14, past_key_15]
        past_values = [past_value_0, past_value_1, past_value_2, past_value_3,
                       past_value_4, past_value_5, past_value_6, past_value_7,
                       past_value_8, past_value_9, past_value_10, past_value_11,
                       past_value_12, past_value_13, past_value_14, past_value_15]

        # Embed the single input token (baked into graph, no separate session call)
        inputs_embeds = self.embed_tokens(input_ids)  # [1, 1, HIDDEN_SIZE]

        # Compute write position in the KV cache
        cache_pos = prefill_len + step  # [1] — where to write new KV entry

        # Build 4D causal attention mask directly, bypassing create_causal_mask()
        # which generates a GatherND op that breaks CUDA graph capture.
        # Shape: [1, 1, 1, MAX_SEQ] — 0.0 for attended, min_dtype for masked
        min_dtype = torch.finfo(inputs_embeds.dtype).min
        positions = torch.arange(self.max_seq, device=input_ids.device)
        attend = positions < (cache_pos + 1)  # [MAX_SEQ] bool
        attention_mask = torch.where(
            attend.view(1, 1, 1, -1),
            torch.tensor(0.0, dtype=inputs_embeds.dtype, device=input_ids.device),
            torch.tensor(min_dtype, dtype=inputs_embeds.dtype, device=input_ids.device),
        )

        # Build 3D M-RoPE position IDs for decode step.
        # During decode, all 3 dims (temporal, height, width) get the same value
        # because we're generating text tokens (not vision tokens).
        position_ids = cache_pos.view(1, 1, 1).expand(3, 1, 1).contiguous()

        # Build WhereStaticCache (uses Where op instead of ScatterND)
        past_key_values = WhereStaticCache(
            config=self.config,
            max_cache_len=self.max_seq,
        )

        # Inject the input KV buffers into the cache layers
        for layer_idx in range(NUM_LAYERS):
            layer = past_key_values.layers[layer_idx]
            layer.keys = past_keys[layer_idx]
            layer.values = past_values[layer_idx]
            layer.is_initialized = True
            layer.dtype = past_keys[layer_idx].dtype
            layer.device = past_keys[layer_idx].device
            layer.max_batch_size = 1
            layer.num_heads = NUM_KV_HEADS
            layer.k_head_dim = HEAD_DIM
            layer.v_head_dim = HEAD_DIM

        # Run the language model with WhereStaticCache + cache_position
        outputs = self.language_model(
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=True,
            cache_position=cache_pos,
        )

        logits = self.lm_head(outputs.last_hidden_state)  # [1, 1, VOCAB_SIZE]

        # ArgMax for next token — stays on GPU, only 8 bytes to copy per step
        # Cast to f32 before argmax (CUDA EP has no BF16 ArgMax kernel)
        next_token = logits[:, -1, :].float().argmax(dim=-1)  # [1]

        # Extract updated KV cache
        updated_cache = outputs.past_key_values
        result = [next_token]
        for layer_idx in range(NUM_LAYERS):
            result.append(updated_cache.layers[layer_idx].keys)
            result.append(updated_cache.layers[layer_idx].values)

        return tuple(result)


# ── Export functions ──────────────────────────────────────────────────────


class VisionEncoderWrapper(nn.Module):
    """Wraps the vision encoder for ONNX export with pre-computed position IDs.

    The vision encoder's rot_pos_emb() uses Python loops with data-dependent
    shapes (for t, h, w in grid_thw) that torch.onnx.export can't trace.
    This wrapper takes pre-computed pos_ids as input instead, avoiding all
    data-dependent control flow.

    For single-image inference, attention is full (no cu_seqlens chunking).
    The eager attention path in GlmOcrVisionAttention splits by cu_seqlens
    using torch.split(lengths.tolist()), which is also untraceable. We bypass
    this by re-implementing attention inline with standard matmul attention.

    Inputs:
        pixel_values:  [num_patches, 1176] bf16 — flattened image patches
        pos_ids:       [num_patches, 2] int64 — pre-computed (h, w) position pairs
        max_grid_size: [] int64 scalar — max(h, w) for RoPE frequency table

    Output:
        hidden_states: [num_merged_patches, 1536] bf16 — vision embeddings
    """

    def __init__(self, visual_model):
        super().__init__()
        self.patch_embed = visual_model.patch_embed
        self.rotary_pos_emb = visual_model.rotary_pos_emb
        self.blocks = visual_model.blocks
        self.post_layernorm = visual_model.post_layernorm
        self.downsample = visual_model.downsample
        self.merger = visual_model.merger

        # Copy attention config from first block for inline attention
        attn = visual_model.blocks[0].attn
        self._num_heads = attn.num_heads
        self._head_dim = attn.head_dim
        self._scaling = attn.scaling

    def _attention_forward(self, attn_module, hidden_states, position_embeddings):
        """Inline attention: QKV projection → RMSNorm → RoPE → matmul attention.

        Replaces GlmOcrVisionAttention.forward() to avoid the untraceable
        cu_seqlens splitting path. Uses standard scaled dot-product attention
        over the full sequence (single-image, no chunking needed).
        """
        seq_len = hidden_states.shape[0]

        # QKV projection + reshape to [Q, K, V] each [seq, heads, head_dim]
        qkv = attn_module.qkv(hidden_states)
        q, k, v = qkv.reshape(seq_len, 3, self._num_heads, self._head_dim).permute(1, 0, 2, 3).unbind(0)

        # Per-head RMSNorm (applied before RoPE, unusual for this architecture)
        q = attn_module.q_norm(q)
        k = attn_module.k_norm(k)

        # 2D RoPE
        from transformers.models.glm_ocr.modeling_glm_ocr import apply_rotary_pos_emb_vision
        cos, sin = position_embeddings
        q, k = apply_rotary_pos_emb_vision(q, k, cos, sin)

        # Reshape for batched matmul: [seq, heads, dim] → [1, heads, seq, dim]
        q = q.transpose(0, 1).unsqueeze(0)
        k = k.transpose(0, 1).unsqueeze(0)
        v = v.transpose(0, 1).unsqueeze(0)

        # Standard scaled dot-product attention (no mask — bidirectional)
        attn_weights = torch.matmul(q, k.transpose(2, 3)) * self._scaling
        attn_weights = torch.nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(q.dtype)
        attn_output = torch.matmul(attn_weights, v)

        # Reshape back: [1, heads, seq, dim] → [seq, hidden]
        attn_output = attn_output.squeeze(0).transpose(0, 1).reshape(seq_len, -1).contiguous()
        return attn_module.proj(attn_output)

    def forward(self, pixel_values, pos_ids, max_grid_size):
        hidden_states = self.patch_embed(pixel_values)

        # Compute RoPE from pre-computed pos_ids (no data-dependent shapes)
        freqs = self.rotary_pos_emb(max_grid_size)  # [max_grid, head_dim//2]
        rope = freqs[pos_ids].flatten(1)             # [N, head_dim]
        emb = torch.cat((rope, rope), dim=-1)        # [N, head_dim*2]
        position_embeddings = (emb.cos(), emb.sin())

        # Run 24 blocks with inline attention (bypasses cu_seqlens splitting)
        for blk in self.blocks:
            hidden_states = hidden_states + self._attention_forward(
                blk.attn, blk.norm1(hidden_states), position_embeddings,
            )
            hidden_states = hidden_states + blk.mlp(blk.norm2(hidden_states))

        # Post-layernorm + spatial downsample (2×2 merge via Conv2d)
        hidden_states = self.post_layernorm(hidden_states)
        hidden_states = hidden_states.view(-1, 2, 2, hidden_states.shape[-1])
        hidden_states = hidden_states.permute(0, 3, 1, 2)
        hidden_states = self.downsample(hidden_states).view(-1, self.downsample.out_channels)

        # Patch merger (gated MLP)
        return self.merger(hidden_states)


def export_vision_encoder(model, output_dir: Path, dtype):
    """Export the vision encoder directly from the model's native weights.

    Pipeline: wrap visual model → trace in FP32 → MHA optimization →
    convert FP32→BF16 (direct, no FP16 intermediate).

    Tracing in FP32 produces a clean graph that MHA optimization can
    pattern-match on. The FP32→BF16 conversion is lossless for native BF16
    weights (BF16→FP32 upcast for tracing is exact, FP32→BF16 rounds back
    to the same values). Ops without BF16 support in the ONNX schema (Conv,
    LayerNorm, etc.) stay in FP32 with Cast wrappers.

    The wrapper moves M-RoPE position computation outside the ONNX model
    (pos_ids and max_grid_size become inputs), avoiding data-dependent shapes
    that torch.onnx.export can't trace. Attention is inlined as standard
    matmul attention (no cu_seqlens chunking).

    MHA optimization runs on the FP32 graph to fuse attention ops into
    com.microsoft.MultiHeadAttention for FlashAttention on CUDA.
    """
    from optimize_mha_vision import apply_mha_surgery

    print("Exporting vision_encoder_mha.onnx ...")
    # Trace in FP32 for clean graph structure (MHA surgery needs FP32 patterns)
    wrapper = VisionEncoderWrapper(model.model.visual).eval().to(torch.float32)

    # Example inputs: 24×24 grid = 576 patches (standard 336×336 image)
    num_patches = 576
    pixel_values = torch.randn(num_patches, 1176, dtype=torch.float32)
    pos_ids = torch.zeros(num_patches, 2, dtype=torch.long)
    max_grid_size = torch.tensor(24, dtype=torch.long)

    # Fill pos_ids with realistic values for tracing
    idx = 0
    for bh in range(12):
        for bw in range(12):
            for mh in range(2):
                for mw in range(2):
                    pos_ids[idx, 0] = bh * 2 + mh
                    pos_ids[idx, 1] = bw * 2 + mw
                    idx += 1

    raw_path = output_dir / "vision_encoder_raw.onnx"
    mha_path = output_dir / "vision_encoder_mha.onnx"

    torch.onnx.export(
        wrapper,
        (pixel_values, pos_ids, max_grid_size),
        str(raw_path),
        opset_version=17,
        input_names=["pixel_values", "pos_ids", "max_grid_size"],
        output_names=["hidden_states"],
        dynamic_axes={
            "pixel_values": {0: "num_patches"},
            "pos_ids": {0: "num_patches"},
            "hidden_states": {0: "num_merged_patches"},
        },
    )
    _print_size(raw_path)

    # MHA optimization: fuse attention into com.microsoft.MultiHeadAttention
    print("  Applying MHA surgery ...")
    apply_mha_surgery(raw_path, mha_path)
    raw_path.unlink()
    raw_data = raw_path.with_suffix(".onnx.data")
    if raw_data.exists():
        raw_data.unlink()

    # Convert FP32→BF16 (direct, no FP16 intermediate)
    if dtype == torch.bfloat16:
        print("  Converting FP32 → BF16 ...")
        _convert_fp32_to_bf16(mha_path)

    _print_size(mha_path)
    return mha_path


def _convert_fp32_to_bf16(onnx_path: Path):
    """Convert an FP32 ONNX graph to BF16 in-place, with FP32 islands.

    Direct FP32→BF16 conversion (no FP16 intermediate). For ops that lack
    BF16 CUDA kernels (Conv, LayerNorm, Range, etc.), weights stay FP32 and
    Cast nodes wrap their inputs/outputs. FP32 preserves full BF16 precision
    (unlike FP16 which has a narrower exponent range).

    This is lossless for native BF16 weights: the FP32 graph was traced
    from BF16 weights (BF16→FP32 upcast is exact), so FP32→BF16 rounds
    back to the original values.
    """
    from ml_dtypes import bfloat16 as ml_bf16

    FLOAT = onnx.TensorProto.FLOAT        # 1
    BFLOAT16 = onnx.TensorProto.BFLOAT16  # 16

    # Ops without BF16 support in ORT 1.24 CUDA EP (ONNX type constraints reject
    # bfloat16). Fall back to FP32 (not FP16) to preserve native BF16 precision.
    # Tested empirically; see PORTING.md for the full compatibility table.
    FP32_OPS = {
        "Conv", "Einsum", "LayerNormalization", "Range",
        "Sin", "Cos", "Reciprocal", "Squeeze", "ReduceMean",
    }

    model = onnx.load(str(onnx_path))

    # 1. Catalog non-BF16 nodes and their input tensor names
    fp32_input_names = set()   # inputs to FP32 ops (initializers stay FP32)
    non_bf16_count = 0
    for node in model.graph.node:
        if node.op_type in FP32_OPS:
            non_bf16_count += 1
            for name in node.input:
                if name:
                    fp32_input_names.add(name)
    print(f"    {non_bf16_count} non-BF16 node(s)")

    # Build maps
    init_map = {init.name: init for init in model.graph.initializer}
    vi_map = {}
    for vi in list(model.graph.value_info) + list(model.graph.input) + list(model.graph.output):
        vi_map[vi.name] = vi

    # 2. Identify initializers consumed ONLY by FP32 ops (not shared with BF16 ops).
    # These stay FP32; shared initializers become BF16 (Cast nodes handle FP32 ops).
    all_input_names = set()
    for node in model.graph.node:
        for name in node.input:
            if name:
                all_input_names.add(name)

    fp32_only_inits = set()
    for name in fp32_input_names:
        if name in init_map:
            # Check if this init is consumed by ANY non-FP32 op
            shared_with_bf16 = False
            for node in model.graph.node:
                if node.op_type not in FP32_OPS and name in list(node.input):
                    shared_with_bf16 = True
                    break
            if not shared_with_bf16:
                fp32_only_inits.add(name)

    n_bf16 = 0
    n_fp32_kept = 0
    for init in model.graph.initializer:
        if init.data_type != FLOAT:
            continue
        if init.name in fp32_only_inits:
            # Exclusively consumed by FP32 ops → keep FP32
            n_fp32_kept += 1
        else:
            # Everything else (including shared) → BF16
            raw = np.frombuffer(init.raw_data, dtype=np.float32)
            init.raw_data = raw.astype(ml_bf16).tobytes()
            init.data_type = BFLOAT16
            n_bf16 += 1

    # 3. Update all FP32 type annotations to BF16
    # (FP32 op outputs get BF16 too — Cast nodes in step 5 bridge the gap)
    n_vi = 0
    for vi in list(model.graph.value_info) + list(model.graph.input) + list(model.graph.output):
        if vi.type.tensor_type.elem_type == FLOAT:
            vi.type.tensor_type.elem_type = BFLOAT16
            n_vi += 1

    # 4. Update Cast nodes: Cast(to=FLOAT) → Cast(to=BF16)
    n_cast = 0
    for node in model.graph.node:
        if node.op_type == "Cast":
            for attr in node.attribute:
                if attr.name == "to" and attr.i == FLOAT:
                    attr.i = BFLOAT16
                    n_cast += 1

    print(f"    {n_bf16} init→BF16, {n_fp32_kept} init kept FP32, {n_vi} annotations, {n_cast} Casts")

    # 5. Insert Cast nodes around non-BF16 ops (BF16↔FP32)
    original_nodes = list(model.graph.node)
    new_nodes = []
    # Track already-inserted BF16→FP32 casts to avoid duplicates when
    # multiple FP32 ops share the same input tensor.
    bf16_to_fp32_casts = {}  # inp_name → cast_out_name

    for node in original_nodes:
        if node.op_type not in FP32_OPS:
            new_nodes.append(node)
            continue

        # Cast(BF16→FP32) for each BF16 input (including shared BF16 initializers)
        for i, inp_name in enumerate(node.input):
            if not inp_name:
                continue
            # Skip FP32-only initializers (already FP32, no cast needed)
            if inp_name in fp32_only_inits:
                continue
            # Skip non-BF16 initializers
            if inp_name in init_map and init_map[inp_name].data_type != BFLOAT16:
                continue
            # Check if it's a BF16 tensor (value_info or initializer)
            is_bf16 = False
            if inp_name in vi_map and vi_map[inp_name].type.tensor_type.elem_type == BFLOAT16:
                is_bf16 = True
            elif inp_name in init_map and init_map[inp_name].data_type == BFLOAT16:
                is_bf16 = True
            if not is_bf16:
                continue
            if inp_name in bf16_to_fp32_casts:
                # Reuse existing Cast node
                node.input[i] = bf16_to_fp32_casts[inp_name]
            else:
                cast_out = f"{inp_name}__to_fp32"
                cast_node = onnx.helper.make_node(
                    "Cast", inputs=[inp_name], outputs=[cast_out],
                    to=FLOAT, name=f"Cast_bf16_to_fp32_{inp_name}",
                )
                new_vi = model.graph.value_info.add()
                new_vi.name = cast_out
                new_vi.type.tensor_type.elem_type = FLOAT
                if inp_name in vi_map and vi_map[inp_name].type.tensor_type.HasField('shape'):
                    new_vi.type.tensor_type.shape.CopyFrom(
                        vi_map[inp_name].type.tensor_type.shape)
                node.input[i] = cast_out
                new_nodes.append(cast_node)
                bf16_to_fp32_casts[inp_name] = cast_out

        new_nodes.append(node)

        # Cast(FP32→BF16) for each output so downstream BF16 nodes get BF16 data
        for i, out_name in enumerate(node.output):
            if not out_name:
                continue
            tmp_name = f"{out_name}__fp32_out"
            # Create FP32 value_info for the op's actual output
            new_vi = model.graph.value_info.add()
            new_vi.name = tmp_name
            new_vi.type.tensor_type.elem_type = FLOAT
            if out_name in vi_map and vi_map[out_name].type.tensor_type.HasField('shape'):
                new_vi.type.tensor_type.shape.CopyFrom(
                    vi_map[out_name].type.tensor_type.shape)
            cast_node = onnx.helper.make_node(
                "Cast", inputs=[tmp_name], outputs=[out_name],
                to=BFLOAT16, name=f"Cast_fp32_to_bf16_{out_name}",
            )
            node.output[i] = tmp_name
            new_nodes.append(cast_node)

    del model.graph.node[:]
    model.graph.node.extend(new_nodes)

    # Delete old external data file before saving to avoid stale/appended data.
    data_path = Path(str(onnx_path) + ".data")
    if data_path.exists():
        data_path.unlink()

    # Externalize tensors >= 1 KB to avoid padding overhead on tiny tensors.
    # convert_attribute=True ensures Constant node data is also saved externally.
    onnx.save(
        model, str(onnx_path),
        save_as_external_data=True,
        all_tensors_to_one_file=True,
        location=onnx_path.name + ".data",
        size_threshold=1024,
        convert_attribute=True,
    )


def export_embedding(model, output_dir: Path):
    """Export the token embedding table as a standalone ONNX model.

    Input:  input_ids    [batch, seq_len] int64
    Output: inputs_embeds [batch, seq_len, 1536] bf16

    Both batch and seq_len are dynamic axes, so this works for both
    prefill (seq_len = prompt length) and single-token decode steps.
    """
    print("Exporting embedding.onnx ...")
    wrapper = EmbedTokensWrapper(model).eval()

    input_ids = torch.randint(0, VOCAB_SIZE, (1, 32))

    output_path = output_dir / "embedding.onnx"
    torch.onnx.export(
        wrapper,
        (input_ids,),
        str(output_path),
        opset_version=17,
        input_names=["input_ids"],
        output_names=["inputs_embeds"],
        dynamic_axes={
            "input_ids": {0: "batch", 1: "seq_len"},
            "inputs_embeds": {0: "batch", 1: "seq_len"},
        },
    )
    _print_size(output_path)
    return output_path


def export_llm(model, output_dir: Path, dtype):
    """Export the LLM decoder with dynamic KV cache to ONNX.

    This model is used for the **prefill pass** — a single forward pass
    with the full prompt (text tokens + vision embeddings merged in).

    The KV cache uses dynamic past_seq_len (starts at 0 for prefill,
    grows by 1 each decode step). This makes it incompatible with CUDA
    graphs, which require fixed shapes. See export_decoder() and
    DecoderStepWrapper for the CUDA-graph-compatible alternative.

    Input tensors:
      - inputs_embeds   [batch, seq_len, 1536]  — merged text+vision embeddings
      - attention_mask   [batch, total_seq_len]  — 1s for all attended positions
      - position_ids     [3, batch, seq_len]     — M-RoPE 3D positions (t, h, w)
      - past_key_{0..15}   [batch, 8, past_seq_len, 128]  — GQA key cache
      - past_value_{0..15} [batch, 8, past_seq_len, 128]  — GQA value cache

    Output tensors:
      - logits             [batch, seq_len, 59392]   — vocabulary logits
      - present_key_{0..15}   [batch, 8, total_seq_len, 128]  — updated keys
      - present_value_{0..15} [batch, 8, total_seq_len, 128]  — updated values

    Note: position_ids has 3 dimensions for M-RoPE (temporal, height, width).
    For text tokens all 3 values are identical. For vision tokens they encode
    the 2D spatial position within the image grid.
    """
    print("Exporting llm.onnx ...")
    wrapper = LLMWrapper(model).eval().to(dtype)

    batch = 1
    seq_len = 8
    past_len = 4

    inputs_embeds = torch.randn(batch, seq_len, HIDDEN_SIZE, dtype=dtype)
    attention_mask = torch.ones(batch, past_len + seq_len, dtype=torch.long)
    # M-RoPE: 3D position IDs [3, batch, seq_len] — temporal, height, width
    position_ids = (torch.arange(past_len, past_len + seq_len)
                    .view(1, 1, -1).expand(3, batch, -1).contiguous().long())

    past_kv = []
    for _ in range(NUM_LAYERS):
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, past_len, HEAD_DIM, dtype=dtype))
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, past_len, HEAD_DIM, dtype=dtype))

    # Build names and dynamic axes
    input_names = ["inputs_embeds", "attention_mask", "position_ids"]
    output_names = ["logits"]
    dynamic_axes = {
        "inputs_embeds": {0: "batch", 1: "seq_len"},
        "attention_mask": {0: "batch", 1: "total_seq_len"},
        "position_ids": {1: "batch", 2: "seq_len"},
        "logits": {0: "batch", 1: "seq_len"},
    }

    for i in range(NUM_LAYERS):
        input_names.extend([f"past_key_{i}", f"past_value_{i}"])
        output_names.extend([f"present_key_{i}", f"present_value_{i}"])
        dynamic_axes[f"past_key_{i}"] = {0: "batch", 2: "past_seq_len"}
        dynamic_axes[f"past_value_{i}"] = {0: "batch", 2: "past_seq_len"}
        dynamic_axes[f"present_key_{i}"] = {0: "batch", 2: "total_seq_len"}
        dynamic_axes[f"present_value_{i}"] = {0: "batch", 2: "total_seq_len"}

    output_path = output_dir / "llm.onnx"
    all_inputs = (inputs_embeds, attention_mask, position_ids) + tuple(past_kv)

    torch.onnx.export(
        wrapper,
        all_inputs,
        str(output_path),
        input_names=input_names,
        output_names=output_names,
        dynamic_axes=dynamic_axes,
        opset_version=17,
        do_constant_folding=True,
    )
    _print_size(output_path)
    return output_path


# ── Helpers ───────────────────────────────────────────────────────────────


def _print_size(onnx_path: Path):
    onnx_size = onnx_path.stat().st_size / 1024 / 1024
    data_path = Path(str(onnx_path) + ".data")
    data_size = data_path.stat().st_size / 1024 / 1024 if data_path.exists() else 0
    total = onnx_size + data_size
    if data_size > 0:
        print(f"  {onnx_path.name}: {onnx_size:.1f} MB graph + {data_size:.1f} MB data = {total:.1f} MB")
    else:
        print(f"  {onnx_path.name}: {total:.1f} MB")


def _topological_sort(graph):
    """Fix ONNX node ordering after inserting Cast nodes.

    When Cast nodes are inserted around FP32-fallback ops, they may break
    topological order. ORT requires nodes to be ordered such that all
    inputs are defined before they're consumed. This function performs
    a DFS-based topological sort to restore a valid ordering.
    """
    producers = {}
    for node in graph.node:
        for out in node.output:
            producers[out] = node

    input_names = set()
    for inp in graph.input:
        input_names.add(inp.name)
    for init in graph.initializer:
        input_names.add(init.name)

    visited = set()
    ordered = []

    def visit(node):
        node_id = id(node)
        if node_id in visited:
            return
        visited.add(node_id)
        for inp_name in node.input:
            if inp_name in producers and id(producers[inp_name]) not in visited:
                visit(producers[inp_name])
        ordered.append(node)

    for node in graph.node:
        visit(node)

    del graph.node[:]
    graph.node.extend(ordered)


def export_decoder(model, output_dir: Path, max_seq: int, export_dtype=torch.bfloat16):
    """Export the CUDA-graph-friendly decode-step LLM.

    Produces llm_decoder.onnx with all-static shapes:
      - KV cache: [1, 8, MAX_SEQ, 128] (fixed, not growing)
      - Input: input_ids [1, 1] + step [1] + prefill_len [1]
      - Output: next_token [1] (ArgMax built into graph)

    No dynamic_axes — every tensor shape is fixed at export time. This is
    required for CUDA graph capture, which records a sequence of GPU kernel
    launches and replays them. Any shape change would invalidate the capture.

    The model weights use export_dtype (BF16 by default), so no post-export
    conversion is needed.
    """
    print(f"\nExporting llm_decoder.onnx (MAX_SEQ={max_seq}, dtype={export_dtype}) ...")

    wrapper = DecoderStepWrapper(model, max_seq).eval().to(export_dtype)

    batch = 1
    seq = 1

    input_ids = torch.randint(0, VOCAB_SIZE, (batch, seq), dtype=torch.long)
    step = torch.tensor([0], dtype=torch.long)
    prefill_len = torch.tensor([10], dtype=torch.long)

    past_kv = []
    for _ in range(NUM_LAYERS):
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, max_seq, HEAD_DIM, dtype=export_dtype))
        past_kv.append(torch.randn(batch, NUM_KV_HEADS, max_seq, HEAD_DIM, dtype=export_dtype))

    input_names = ["input_ids", "step", "prefill_len"]
    output_names = ["next_token"]

    for i in range(NUM_LAYERS):
        input_names.extend([f"past_key_{i}", f"past_value_{i}"])
        output_names.extend([f"present_key_{i}", f"present_value_{i}"])

    output_path = output_dir / "llm_decoder.onnx"
    all_inputs = (input_ids, step, prefill_len) + tuple(past_kv)

    torch.onnx.export(
        wrapper,
        all_inputs,
        str(output_path),
        input_names=input_names,
        output_names=output_names,
        opset_version=17,
        do_constant_folding=True,
    )

    _print_size(output_path)
    return output_path


def validate_decoder(output_dir: Path, max_seq: int):
    """Validate the exported decoder ONNX loads and produces correct shapes."""
    print("\nValidating llm_decoder.onnx ...")
    decoder_path = output_dir / "llm_decoder.onnx"

    opts = ort.SessionOptions()
    opts.log_severity_level = 3
    session = ort.InferenceSession(str(decoder_path), opts, providers=["CPUExecutionProvider"])

    print("  Session inputs:")
    for inp in session.get_inputs():
        print(f"    {inp.name}: {inp.type} {inp.shape}")
    print("  Session outputs:")
    for out in session.get_outputs():
        print(f"    {out.name}: {out.type} {out.shape}")

    # Test inference
    feed = {
        "input_ids": np.array([[100]], dtype=np.int64),
        "step": np.array([0], dtype=np.int64),
        "prefill_len": np.array([10], dtype=np.int64),
    }
    # Determine KV cache dtype from the model's first KV input
    kv_dtype_str = session.get_inputs()[3].type  # past_key_0
    if "bfloat16" in kv_dtype_str:
        from ml_dtypes import bfloat16 as ml_bf16
        kv_np_dtype = ml_bf16
    else:
        kv_np_dtype = np.float16
    for i in range(NUM_LAYERS):
        feed[f"past_key_{i}"] = np.zeros(
            (1, NUM_KV_HEADS, max_seq, HEAD_DIM), dtype=kv_np_dtype
        )
        feed[f"past_value_{i}"] = np.zeros(
            (1, NUM_KV_HEADS, max_seq, HEAD_DIM), dtype=kv_np_dtype
        )

    outputs = session.run(None, feed)
    next_token = outputs[0]
    print(f"  next_token: {next_token} (shape={next_token.shape}, dtype={next_token.dtype})")

    for i in range(NUM_LAYERS):
        k = outputs[1 + i * 2]
        v = outputs[2 + i * 2]
        assert k.shape == (1, NUM_KV_HEADS, max_seq, HEAD_DIM), \
            f"present_key_{i} shape mismatch: {k.shape}"
        assert v.shape == (1, NUM_KV_HEADS, max_seq, HEAD_DIM), \
            f"present_value_{i} shape mismatch: {v.shape}"

    print("  PASS: all shapes correct")


def validate_llm(wrapper, output_dir: Path, dtype):
    """Validate LLM ONNX output matches PyTorch within precision tolerance.

    Runs both models on the same random input and checks that the logits
    max absolute difference is within tolerance:
      - FP16: < 1.0 (FP16 has limited precision, large logit magnitudes)
      - FP32: < 0.01
    """
    print("\nValidating LLM ...")
    output_path = output_dir / "llm.onnx"
    opts = ort.SessionOptions()
    opts.log_severity_level = 3
    session = ort.InferenceSession(str(output_path), opts, providers=["CPUExecutionProvider"])

    print(f"  Prefill test (dtype={dtype}) ...", flush=True)
    embeds = torch.randn(1, 16, HIDDEN_SIZE, dtype=dtype)
    mask = torch.ones(1, 16, dtype=torch.long)
    pos = torch.arange(16).view(1, 1, -1).expand(3, 1, -1).contiguous().long()
    empty_kv = [torch.zeros(1, NUM_KV_HEADS, 0, HEAD_DIM, dtype=dtype)
                for _ in range(NUM_LAYERS * 2)]

    wrapper = wrapper.to(dtype)
    with torch.no_grad():
        pt_out = wrapper(embeds, mask, pos, *empty_kv)

    onnx_feed = {
        "inputs_embeds": embeds.numpy(),
        "attention_mask": mask.numpy(),
        "position_ids": pos.numpy(),
    }
    for i in range(NUM_LAYERS):
        onnx_feed[f"past_key_{i}"] = empty_kv[i * 2].numpy()
        onnx_feed[f"past_value_{i}"] = empty_kv[i * 2 + 1].numpy()

    onnx_out = session.run(None, onnx_feed)
    diff = np.abs(pt_out[0].float().numpy() - onnx_out[0].astype(np.float32)).max()
    threshold = 1.0 if dtype == torch.float16 else 0.01
    print(f"    logits max diff: {diff:.2e} {'PASS' if diff < threshold else 'FAIL'}")


# ── Main ──────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Export GLM-OCR to ONNX")
    parser.add_argument("--output-dir", type=str, default=DEFAULT_OUTPUT_DIR)
    dtype_group = parser.add_mutually_exclusive_group()
    dtype_group.add_argument("--fp32", action="store_true",
                             help="Export in FP32 (debug)")
    dtype_group.add_argument("--bf16", action="store_true",
                             help="Export all models in BF16 (requires CUDA)")
    parser.add_argument("--skip-vision", action="store_true",
                        help="Skip vision encoder export (use existing file)")
    parser.add_argument("--skip-decoder", action="store_true",
                        help="Skip CUDA-graph decoder export")
    parser.add_argument("--max-seq", type=int, default=DEFAULT_MAX_SEQ,
                        help=f"Max sequence length for decoder KV cache (default: {DEFAULT_MAX_SEQ})")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Determine export dtype for embedding + LLM
    if args.fp32:
        export_dtype = torch.float32
    elif args.bf16:
        export_dtype = torch.bfloat16
    else:
        export_dtype = torch.float16

    print(f"Export dtype: {export_dtype}")
    print(f"Loading {MODEL_ID} (native BF16) ...")
    t0 = time.perf_counter()
    model = AutoModelForImageTextToText.from_pretrained(MODEL_ID)  # loads as BF16
    model.eval()
    if export_dtype != torch.bfloat16:
        model.to(export_dtype)  # BF16 -> FP16 or FP32
    print(f"Loaded in {time.perf_counter() - t0:.1f}s\n")

    # Save processor/tokenizer/config for inference.
    # These files are needed by both Python (AutoProcessor.from_pretrained)
    # and Rust (reads tokenizer.json directly) inference code. They are
    # downloaded from HuggingFace and saved locally so inference doesn't
    # need network access.
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    processor.save_pretrained(str(output_dir))
    config = AutoConfig.from_pretrained(MODEL_ID)
    config.save_pretrained(str(output_dir))
    print(f"Saved processor and config to {output_dir}\n")

    with torch.no_grad():
        # ── Shared models (used by both prefill and non-CUDA-graph decode) ──
        export_embedding(model, output_dir)

        # ── Prefill LLM (dynamic KV cache, runs once per image) ──
        export_llm(model, output_dir, export_dtype)

        # ── Vision encoder (native BF16 → FP32 trace → MHA optimize → FP32→BF16) ──
        if args.skip_vision:
            print("Skipping vision encoder (--skip-vision)")
        else:
            export_vision_encoder(model, output_dir, export_dtype)

        # ── Decode-step LLM (fixed KV cache, CUDA graph compatible) ──
        if args.skip_decoder:
            print("\nSkipping decoder (--skip-decoder)")
        else:
            export_decoder(model, output_dir, args.max_seq, export_dtype)
            # GQA attention fusion on the exported decoder
            from optimize_gqa import apply_gqa_surgery
            decoder_path = output_dir / "llm_decoder.onnx"
            gqa_path = output_dir / "llm_decoder_gqa.onnx"
            apply_gqa_surgery(decoder_path, gqa_path, args.max_seq)

    # ── Validation ──
    if args.bf16:
        print("\nSkipping validation (BF16 requires CUDA)")
    else:
        llm_wrapper = LLMWrapper(model).eval()
        validate_llm(llm_wrapper, output_dir, export_dtype)
        if not args.skip_decoder:
            validate_decoder(output_dir, args.max_seq)

    # ── Summary ──
    print(f"\n{'='*50}")
    print("Export complete. Files:")
    total = 0
    for f in sorted(output_dir.glob("*.onnx*")):
        if f.suffix in ('.onnx', '.data'):
            sz = f.stat().st_size / 1024 / 1024
            total += sz
            print(f"  {f.name:40s} {sz:>8.1f} MB")
    print(f"  {'TOTAL':40s} {total:>8.1f} MB")
    if args.bf16:
        print("\nNote: BF16 models require CUDA. Non-BF16 ops (Conv, LayerNorm, Range) use FP32 fallback.")


if __name__ == "__main__":
    main()
